// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQueue() {
  return window['go']['main']['App']['CancelQueue']();
}

export function CheckPlatformLogin(arg1) {
  return window['go']['main']['App']['CheckPlatformLogin'](arg1);
}

export function GenerateSlots(arg1, arg2) {
  return window['go']['main']['App']['GenerateSlots'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetPendingJobs() {
  return window['go']['main']['App']['GetPendingJobs']();
}

export function GetSchedulerStatus() {
  return window['go']['main']['App']['GetSchedulerStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSupportedPlatforms() {
  return window['go']['main']['App']['GetSupportedPlatforms']();
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function IsCloseToTray() {
  return window['go']['main']['App']['IsCloseToTray']();
}

export function IsQuitting() {
  return window['go']['main']['App']['IsQuitting']();
}

export function IsUploading() {
  return window['go']['main']['App']['IsUploading']();
}

export function IsWindowVisible() {
  return window['go']['main']['App']['IsWindowVisible']();
}

export function OpenChromeForLogin() {
  return window['go']['main']['App']['OpenChromeForLogin']();
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function OpenPlatformLogin(arg1) {
  return window['go']['main']['App']['OpenPlatformLogin'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RegisterSettingsUpdateListener(arg1) {
  return window['go']['main']['App']['RegisterSettingsUpdateListener'](arg1);
}

export function ResumeQueue() {
  return window['go']['main']['App']['ResumeQueue']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetPublishMode(arg1) {
  return window['go']['main']['App']['SetPublishMode'](arg1);
}

export function SetWindowVisible(arg1) {
  return window['go']['main']['App']['SetWindowVisible'](arg1);
}

export function ShowApp() {
  return window['go']['main']['App']['ShowApp']();
}

export function StartOmnichannelUpload(arg1, arg2) {
  return window['go']['main']['App']['StartOmnichannelUpload'](arg1, arg2);
}

export function StartUpload(arg1) {
  return window['go']['main']['App']['StartUpload'](arg1);
}

export function StopUpload() {
  return window['go']['main']['App']['StopUpload']();
}

export function ToggleAppWindow() {
  return window['go']['main']['App']['ToggleAppWindow']();
}

export function ToggleAutoUpload(arg1) {
  return window['go']['main']['App']['ToggleAutoUpload'](arg1);
}

export function TriggerAutoUploadNow() {
  return window['go']['main']['App']['TriggerAutoUploadNow']();
}

export function UpdateGoldenHours(arg1) {
  return window['go']['main']['App']['UpdateGoldenHours'](arg1);
}
