// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {ports} from '../models';

export function CancelQueue():Promise<void>;

export function CheckPlatformLogin(arg1:string):Promise<boolean>;

export function GenerateSlots(arg1:Array<domain.VideoItem>,arg2:string):Promise<Array<domain.VideoItem>>;

export function GetAppVersion():Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetHistory():Promise<Array<domain.HistoryRecord>>;

export function GetPendingJobs():Promise<Array<ports.JobItem>>;

export function GetSchedulerStatus():Promise<Record<string, any>>;

export function GetSettings():Promise<domain.Settings>;

export function GetSupportedPlatforms():Promise<Array<domain.PlatformInfo>>;

export function HideApp():Promise<void>;

export function IsCloseToTray():Promise<boolean>;

export function IsQuitting():Promise<boolean>;

export function IsUploading():Promise<boolean>;

export function IsWindowVisible():Promise<boolean>;

export function OpenChromeForLogin():Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function OpenPlatformLogin(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RegisterSettingsUpdateListener(arg1:any):Promise<void>;

export function ResumeQueue():Promise<void>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;

export function ScanFolder(arg1:string):Promise<Array<domain.VideoItem>>;

export function SelectFolder():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetPublishMode(arg1:string):Promise<void>;

export function SetWindowVisible(arg1:boolean):Promise<void>;

export function ShowApp():Promise<void>;

export function StartOmnichannelUpload(arg1:Array<domain.VideoItem>,arg2:Array<string>):Promise<void>;

export function StartUpload(arg1:Array<domain.VideoItem>):Promise<void>;

export function StopUpload():Promise<void>;

export function ToggleAppWindow():Promise<void>;

export function ToggleAutoUpload(arg1:boolean):Promise<void>;

export function TriggerAutoUploadNow():Promise<void>;

export function UpdateGoldenHours(arg1:Array<string>):Promise<void>;
